pool:
  name: NonTVBuilds
variables:
  SemVerPrereleaseTag: 'merchants.OM.Api'

name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)-$(SemVerPrereleaseTag)
steps:
- script: echo $(Build.BuildNumber) #display Run Number

- task: VSBuild@1
  displayName: 'merchants.OM.Api'
  inputs:
    solution: OM.Api.sln
    vsVersion: 16.0
    msbuildArgs: '/target:publish'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    maximumCpuCount: true
    msbuildArchitecture: x64
  enabled: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(SemVerPrereleaseTag)'
  condition: succeededOrFailed()
  
