pool:
  name: NonTVBuilds
variables:
  SemVerPrereleaseTag: 'WebApplication3'

name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)-$(SemVerPrereleaseTag)
steps:
- script: echo $(Build.BuildNumber) #display Run Number

- task: VSBuild@1
  displayName: 'WebApplication3'
  inputs:
    solution: WebApplication3.sln
    msbuildArgs: '/target:publish'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    maximumCpuCount: true
    msbuildArchitecture: x64
  enabled: true

- task: CopyFiles@2
  inputs:
    contents: 'Publish Artifact'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(SemVerPrereleaseTag)'
  condition: succeededOrFailed()
  
