# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: NonTVBuilds

variables:
  SemVerPrereleaseTag: MVC Application'

name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)-$(SemVerPrereleaseTag)
steps:
- script: echo $(Build.BuildNumber) #display Run Number

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

-  task: VSBuild@1
  inputs:
    solution: WebApplication3.sln
    vsVersion: 1.0
    msbuildArgs: '/target:publish'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    maximumCpuCount: true
    msbuildArchitecture: x64
  enabled: true

  - task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(SemVerPrereleaseTag)'
  condition: succeededOrFailed()
